# Setup
title:        PDFUnisci
tagline:      Merge and split PDF with a simple right click using itextsharp.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Claudio Mola
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

show_downloads: "true"